// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpnzpiileyneehtihivc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbnpwaWlsZXluZWVodGloaXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDI2NDYsImV4cCI6MjA3MTc3ODY0Nn0.RGfmqmVMW6Vv1SIKRX-2BrFelktZnKU35447ykUb_tQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});